# SPDX-License-Identifier: Apache-2.0
#fix
name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["build","ci","docs","feat","fix","perf","refactor","style","test","feat!"]'
          custom_labels: '{"build": "build", "ci": "CI/CD", "docs": "documentation", "feat": "feature", "fix": "bug", "perf": "performance", "refactor": "refactor", "style": "style", "test": "test", "feat!": "feature breaking change"}'
          token: ${{ secrets.PAT }}
          add_label: 'true'