# SPDX-License-Identifier: Apache-2.0

name: DCO

on: [pull_request]

jobs:
  dco:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Check for DCO Sign-off
      run: |
        commits=$(git log --pretty=format:%H origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }})
        non_compliant_commits=""

        # Check each commit for a Signed-off-by line
        for commit in $commits; do
          if ! git show --quiet --format=%B $commit | grep -q "^Signed-off-by: "; then
            non_compliant_commits="$non_compliant_commits $commit"
          fi
        done

        if [ -n "$non_compliant_commits" ]; then
          echo "The following commits do not have a Signed-off-by line:"
          for commit in $non_compliant_commits; do
            echo "- $commit"
          done
          exit 1
        fi
      shell: bash
