# SPDX-License-Identifier: Apache-2.0

name: GPG Verify

on: [pull_request]

jobs:
  gpg-verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Check GPG verification status
      run: |
        commits=$(git log --pretty=format:%H origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }})
        for commit in $commits; do
          status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/commits/$commit/check-runs \
            | jq -r '.check_runs[] | select(.name == "GPG verify") | .conclusion')
          if [[ "$status" != "success" ]]; then
            echo "GPG signature verification failed for commit $commit."
            exit 1
          fi
        done
