# SPDX-License-Identifier: Apache-2.0

name: Sync Workflows

on:
  pull_request:
    types: [closed]

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Central Workflows Repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config --global credential.helper store

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://github.com/cli/cli/releases/download/v2.14.7/gh_2.14.7_linux_amd64.tar.gz -o ghcli.tar.gz 
          tar -xzf ghcli.tar.gz
          sudo cp gh_2.14.7_linux_amd64/bin/gh /usr/local/bin/

      - name: Get PR author details
        id: pr_author
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_AUTHOR_NAME=$(gh api "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" --jq '.user.login')
          PR_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          PR_AUTHOR_NAME_FULL=$(git log -1 --pretty=format:'%an')
          echo "PR_AUTHOR_NAME=${PR_AUTHOR_NAME}" >> $GITHUB_ENV
          echo "PR_AUTHOR_EMAIL=${PR_AUTHOR_EMAIL}" >> $GITHUB_ENV
          echo "PR_AUTHOR_NAME_FULL=${PR_AUTHOR_NAME_FULL}" >> $GITHUB_ENV
          
      - name: Sync Workflows to Other Repos
        env:
          REPOS: |
            typology-processor
            channel-router-setup-processor
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          SIGNED_OFF_BY="Signed-off-by: ${{ env.PR_AUTHOR_NAME_FULL }} <${{ env.PR_AUTHOR_EMAIL }}>"
          for repo in $REPOS; do
            git clone https://github.com/vorsterk/$repo.git
            cd $repo
            git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/vorsterk/$repo.git
            git checkout -b sync-workflows-update
            git pull --rebase origin dev
            cd ..
            mkdir -p temp-workflows
            cp -r .github/workflows/* temp-workflows/
            rm temp-workflows/sync-workflows.yml
            cp -r temp-workflows/* $repo/.github/workflows/
            cd $repo
            git add .
            git commit -m "chore: sync workflows from central-workflows\n\n${SIGNED_OFF_BY}"
            git push origin sync-workflows-update
            
            # Clear the GITHUB_TOKEN environment variable and use a temporary file for gh authentication
            echo "${{ secrets.PAT }}" > /tmp/gh_token
            unset GITHUB_TOKEN
            gh auth login --with-token < /tmp/gh_token
            gh pr create --title "chore: sync workflows from central-workflows" --body "This PR syncs workflows from the central-workflows repository.\n\n${SIGNED_OFF_BY}" --base dev --head sync-workflows-update
            
            # Cleanup
            rm /tmp/gh_token
            
            cd ..
          done
